# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ARINC485.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ARINC485.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x0e\x41RINC485.proto\x12\x07mpsqual\"|\n\x0f\x41RINC485Request\x12:\n\x0brequestType\x18\x01 \x02(\x0e\x32%.mpsqual.ARINC485Request.RequestTypeT\"-\n\x0cRequestTypeT\x12\x08\n\x04STOP\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\n\n\x06REPORT\x10\x02\"\xee\x01\n\x10\x41RINC485Response\x12\x32\n\x05state\x18\x01 \x02(\x0e\x32#.mpsqual.ARINC485Response.AppStateT\x12;\n\nstatistics\x18\x02 \x03(\x0b\x32\'.mpsqual.ARINC485Response.LoopbackStats\x1a\x42\n\rLoopbackStats\x12\x0f\n\x07\x63hannel\x18\x01 \x02(\t\x12\x0e\n\x06missed\x18\x02 \x02(\r\x12\x10\n\x08received\x18\x03 \x02(\r\"%\n\tAppStateT\x12\x0b\n\x07STOPPED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ARINC485REQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.ARINC485Request.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=106,
  serialized_end=151,
)
_sym_db.RegisterEnumDescriptor(_ARINC485REQUEST_REQUESTTYPET)

_ARINC485RESPONSE_APPSTATET = _descriptor.EnumDescriptor(
  name='AppStateT',
  full_name='mpsqual.ARINC485Response.AppStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=355,
  serialized_end=392,
)
_sym_db.RegisterEnumDescriptor(_ARINC485RESPONSE_APPSTATET)


_ARINC485REQUEST = _descriptor.Descriptor(
  name='ARINC485Request',
  full_name='mpsqual.ARINC485Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.ARINC485Request.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ARINC485REQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=151,
)


_ARINC485RESPONSE_LOOPBACKSTATS = _descriptor.Descriptor(
  name='LoopbackStats',
  full_name='mpsqual.ARINC485Response.LoopbackStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='mpsqual.ARINC485Response.LoopbackStats.channel', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='missed', full_name='mpsqual.ARINC485Response.LoopbackStats.missed', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='received', full_name='mpsqual.ARINC485Response.LoopbackStats.received', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=353,
)

_ARINC485RESPONSE = _descriptor.Descriptor(
  name='ARINC485Response',
  full_name='mpsqual.ARINC485Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='mpsqual.ARINC485Response.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statistics', full_name='mpsqual.ARINC485Response.statistics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ARINC485RESPONSE_LOOPBACKSTATS, ],
  enum_types=[
    _ARINC485RESPONSE_APPSTATET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=392,
)

_ARINC485REQUEST.fields_by_name['requestType'].enum_type = _ARINC485REQUEST_REQUESTTYPET
_ARINC485REQUEST_REQUESTTYPET.containing_type = _ARINC485REQUEST
_ARINC485RESPONSE_LOOPBACKSTATS.containing_type = _ARINC485RESPONSE
_ARINC485RESPONSE.fields_by_name['state'].enum_type = _ARINC485RESPONSE_APPSTATET
_ARINC485RESPONSE.fields_by_name['statistics'].message_type = _ARINC485RESPONSE_LOOPBACKSTATS
_ARINC485RESPONSE_APPSTATET.containing_type = _ARINC485RESPONSE
DESCRIPTOR.message_types_by_name['ARINC485Request'] = _ARINC485REQUEST
DESCRIPTOR.message_types_by_name['ARINC485Response'] = _ARINC485RESPONSE

ARINC485Request = _reflection.GeneratedProtocolMessageType('ARINC485Request', (_message.Message,), dict(
  DESCRIPTOR = _ARINC485REQUEST,
  __module__ = 'ARINC485_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.ARINC485Request)
  ))
_sym_db.RegisterMessage(ARINC485Request)

ARINC485Response = _reflection.GeneratedProtocolMessageType('ARINC485Response', (_message.Message,), dict(

  LoopbackStats = _reflection.GeneratedProtocolMessageType('LoopbackStats', (_message.Message,), dict(
    DESCRIPTOR = _ARINC485RESPONSE_LOOPBACKSTATS,
    __module__ = 'ARINC485_pb2'
    # @@protoc_insertion_point(class_scope:mpsqual.ARINC485Response.LoopbackStats)
    ))
  ,
  DESCRIPTOR = _ARINC485RESPONSE,
  __module__ = 'ARINC485_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.ARINC485Response)
  ))
_sym_db.RegisterMessage(ARINC485Response)
_sym_db.RegisterMessage(ARINC485Response.LoopbackStats)


# @@protoc_insertion_point(module_scope)
