# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ARINC717Frame.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ARINC717Frame.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x13\x41RINC717Frame.proto\x12\x07mpsqual\"\x8c\x01\n\x14\x41RINC717FrameRequest\x12\x45\n\x0brequestType\x18\x01 \x02(\x0e\x32*.mpsqual.ARINC717FrameRequest.RequestTypeT:\x04STOP\"-\n\x0cRequestTypeT\x12\x08\n\x04STOP\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\n\n\x06REPORT\x10\x02\"\xfa\x01\n\x15\x41RINC717FrameResponse\x12\x37\n\x05state\x18\x01 \x02(\x0e\x32(.mpsqual.ARINC717FrameResponse.AppStateT\x12\x44\n\tsyncState\x18\x02 \x02(\x0e\x32(.mpsqual.ARINC717FrameResponse.FrameSync:\x07NO_SYNC\x12\x15\n\rarinc717frame\x18\x03 \x03(\x05\"%\n\tAppStateT\x12\x0b\n\x07STOPPED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\"$\n\tFrameSync\x12\x0b\n\x07NO_SYNC\x10\x00\x12\n\n\x06SYNCED\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ARINC717FRAMEREQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.ARINC717FrameRequest.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=128,
  serialized_end=173,
)
_sym_db.RegisterEnumDescriptor(_ARINC717FRAMEREQUEST_REQUESTTYPET)

_ARINC717FRAMERESPONSE_APPSTATET = _descriptor.EnumDescriptor(
  name='AppStateT',
  full_name='mpsqual.ARINC717FrameResponse.AppStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=351,
  serialized_end=388,
)
_sym_db.RegisterEnumDescriptor(_ARINC717FRAMERESPONSE_APPSTATET)

_ARINC717FRAMERESPONSE_FRAMESYNC = _descriptor.EnumDescriptor(
  name='FrameSync',
  full_name='mpsqual.ARINC717FrameResponse.FrameSync',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_SYNC', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYNCED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=390,
  serialized_end=426,
)
_sym_db.RegisterEnumDescriptor(_ARINC717FRAMERESPONSE_FRAMESYNC)


_ARINC717FRAMEREQUEST = _descriptor.Descriptor(
  name='ARINC717FrameRequest',
  full_name='mpsqual.ARINC717FrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.ARINC717FrameRequest.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ARINC717FRAMEREQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=173,
)


_ARINC717FRAMERESPONSE = _descriptor.Descriptor(
  name='ARINC717FrameResponse',
  full_name='mpsqual.ARINC717FrameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='mpsqual.ARINC717FrameResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='syncState', full_name='mpsqual.ARINC717FrameResponse.syncState', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arinc717frame', full_name='mpsqual.ARINC717FrameResponse.arinc717frame', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ARINC717FRAMERESPONSE_APPSTATET,
    _ARINC717FRAMERESPONSE_FRAMESYNC,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=426,
)

_ARINC717FRAMEREQUEST.fields_by_name['requestType'].enum_type = _ARINC717FRAMEREQUEST_REQUESTTYPET
_ARINC717FRAMEREQUEST_REQUESTTYPET.containing_type = _ARINC717FRAMEREQUEST
_ARINC717FRAMERESPONSE.fields_by_name['state'].enum_type = _ARINC717FRAMERESPONSE_APPSTATET
_ARINC717FRAMERESPONSE.fields_by_name['syncState'].enum_type = _ARINC717FRAMERESPONSE_FRAMESYNC
_ARINC717FRAMERESPONSE_APPSTATET.containing_type = _ARINC717FRAMERESPONSE
_ARINC717FRAMERESPONSE_FRAMESYNC.containing_type = _ARINC717FRAMERESPONSE
DESCRIPTOR.message_types_by_name['ARINC717FrameRequest'] = _ARINC717FRAMEREQUEST
DESCRIPTOR.message_types_by_name['ARINC717FrameResponse'] = _ARINC717FRAMERESPONSE

ARINC717FrameRequest = _reflection.GeneratedProtocolMessageType('ARINC717FrameRequest', (_message.Message,), dict(
  DESCRIPTOR = _ARINC717FRAMEREQUEST,
  __module__ = 'ARINC717Frame_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.ARINC717FrameRequest)
  ))
_sym_db.RegisterMessage(ARINC717FrameRequest)

ARINC717FrameResponse = _reflection.GeneratedProtocolMessageType('ARINC717FrameResponse', (_message.Message,), dict(
  DESCRIPTOR = _ARINC717FRAMERESPONSE,
  __module__ = 'ARINC717Frame_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.ARINC717FrameResponse)
  ))
_sym_db.RegisterMessage(ARINC717FrameResponse)


# @@protoc_insertion_point(module_scope)
