# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ARINC429.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ARINC429.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x0e\x41RINC429.proto\x12\x07mpsqual\"\xb4\x01\n\x0f\x41RINC429Request\x12\x46\n\x0brequestType\x18\x01 \x02(\x0e\x32%.mpsqual.ARINC429Request.RequestTypeT:\nDISCONNECT\x12\x0e\n\x04sink\x18\x02 \x02(\t:\x00\x12\x10\n\x06source\x18\x03 \x01(\t:\x00\"7\n\x0cRequestTypeT\x12\x0e\n\nDISCONNECT\x10\x00\x12\x0b\n\x07\x43ONNECT\x10\x01\x12\n\n\x06REPORT\x10\x02\"\x9a\x02\n\x10\x41RINC429Response\x12\x37\n\x06status\x18\x01 \x03(\x0b\x32\'.mpsqual.ARINC429Response.StatusMessage\x1a\x9e\x01\n\rStatusMessage\x12\x0c\n\x04sink\x18\x01 \x02(\t\x12\x10\n\x06source\x18\x02 \x02(\t:\x00\x12\x35\n\x08\x63onState\x18\x03 \x02(\x0e\x32#.mpsqual.ARINC429Response.ConStateT\x12\x10\n\x08xmtCount\x18\x04 \x02(\r\x12\x10\n\x08rcvCount\x18\x05 \x02(\r\x12\x12\n\nerrorCount\x18\x06 \x02(\r\",\n\tConStateT\x12\x10\n\x0c\x44ISCONNECTED\x10\x00\x12\r\n\tCONNECTED\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ARINC429REQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.ARINC429Request.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=153,
  serialized_end=208,
)
_sym_db.RegisterEnumDescriptor(_ARINC429REQUEST_REQUESTTYPET)

_ARINC429RESPONSE_CONSTATET = _descriptor.EnumDescriptor(
  name='ConStateT',
  full_name='mpsqual.ARINC429Response.ConStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=449,
  serialized_end=493,
)
_sym_db.RegisterEnumDescriptor(_ARINC429RESPONSE_CONSTATET)


_ARINC429REQUEST = _descriptor.Descriptor(
  name='ARINC429Request',
  full_name='mpsqual.ARINC429Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.ARINC429Request.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sink', full_name='mpsqual.ARINC429Request.sink', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='mpsqual.ARINC429Request.source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ARINC429REQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=208,
)


_ARINC429RESPONSE_STATUSMESSAGE = _descriptor.Descriptor(
  name='StatusMessage',
  full_name='mpsqual.ARINC429Response.StatusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sink', full_name='mpsqual.ARINC429Response.StatusMessage.sink', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='mpsqual.ARINC429Response.StatusMessage.source', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='conState', full_name='mpsqual.ARINC429Response.StatusMessage.conState', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xmtCount', full_name='mpsqual.ARINC429Response.StatusMessage.xmtCount', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rcvCount', full_name='mpsqual.ARINC429Response.StatusMessage.rcvCount', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorCount', full_name='mpsqual.ARINC429Response.StatusMessage.errorCount', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=447,
)

_ARINC429RESPONSE = _descriptor.Descriptor(
  name='ARINC429Response',
  full_name='mpsqual.ARINC429Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='mpsqual.ARINC429Response.status', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ARINC429RESPONSE_STATUSMESSAGE, ],
  enum_types=[
    _ARINC429RESPONSE_CONSTATET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=493,
)

_ARINC429REQUEST.fields_by_name['requestType'].enum_type = _ARINC429REQUEST_REQUESTTYPET
_ARINC429REQUEST_REQUESTTYPET.containing_type = _ARINC429REQUEST
_ARINC429RESPONSE_STATUSMESSAGE.fields_by_name['conState'].enum_type = _ARINC429RESPONSE_CONSTATET
_ARINC429RESPONSE_STATUSMESSAGE.containing_type = _ARINC429RESPONSE
_ARINC429RESPONSE.fields_by_name['status'].message_type = _ARINC429RESPONSE_STATUSMESSAGE
_ARINC429RESPONSE_CONSTATET.containing_type = _ARINC429RESPONSE
DESCRIPTOR.message_types_by_name['ARINC429Request'] = _ARINC429REQUEST
DESCRIPTOR.message_types_by_name['ARINC429Response'] = _ARINC429RESPONSE

ARINC429Request = _reflection.GeneratedProtocolMessageType('ARINC429Request', (_message.Message,), dict(
  DESCRIPTOR = _ARINC429REQUEST,
  __module__ = 'ARINC429_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.ARINC429Request)
  ))
_sym_db.RegisterMessage(ARINC429Request)

ARINC429Response = _reflection.GeneratedProtocolMessageType('ARINC429Response', (_message.Message,), dict(

  StatusMessage = _reflection.GeneratedProtocolMessageType('StatusMessage', (_message.Message,), dict(
    DESCRIPTOR = _ARINC429RESPONSE_STATUSMESSAGE,
    __module__ = 'ARINC429_pb2'
    # @@protoc_insertion_point(class_scope:mpsqual.ARINC429Response.StatusMessage)
    ))
  ,
  DESCRIPTOR = _ARINC429RESPONSE,
  __module__ = 'ARINC429_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.ARINC429Response)
  ))
_sym_db.RegisterMessage(ARINC429Response)
_sym_db.RegisterMessage(ARINC429Response.StatusMessage)


# @@protoc_insertion_point(module_scope)
