# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CarrierCardData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CarrierCardData.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x15\x43\x61rrierCardData.proto\x12\x07mpsqual\"\xc1\x01\n\x16\x43\x61rrierCardDataRequest\x12\x41\n\x0brequestType\x18\x01 \x02(\x0e\x32,.mpsqual.CarrierCardDataRequest.RequestTypeT\x12!\n\x06values\x18\x02 \x03(\x0b\x32\x11.mpsqual.Property\"A\n\x0cRequestTypeT\x12\x08\n\x04READ\x10\x00\x12\t\n\x05WRITE\x10\x01\x12\t\n\x05\x45RASE\x10\x02\x12\x11\n\rWRITE_PROTECT\x10\x03\"\x87\x01\n\x17\x43\x61rrierCardDataResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12 \n\x05\x65rror\x18\x02 \x01(\x0b\x32\x11.mpsqual.ErrorMsg\x12\x16\n\x0ewriteProtected\x18\x03 \x01(\x08\x12!\n\x06values\x18\x04 \x03(\x0b\x32\x11.mpsqual.Property\"&\n\x08Property\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\xed\x01\n\x08\x45rrorMsg\x12\x12\n\nerror_code\x18\x01 \x02(\r\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\xb7\x01\n\x07\x45rrCode\x12\x1c\n\x17\x46\x41ILURE_INVALID_MESSAGE\x10\xe8\x07\x12\x18\n\x13\x46\x41ILURE_INVALID_KEY\x10\xe9\x07\x12\x1a\n\x15\x46\x41ILURE_INVALID_VALUE\x10\xea\x07\x12#\n\x1e\x46\x41ILURE_WRITE_PROTECT_DISABLED\x10\xeb\x07\x12\x18\n\x13\x46\x41ILURE_READ_FAILED\x10\xec\x07\x12\x19\n\x14\x46\x41ILURE_WRITE_FAILED\x10\xed\x07')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CARRIERCARDDATAREQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.CarrierCardDataRequest.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='READ', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRITE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERASE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRITE_PROTECT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=163,
  serialized_end=228,
)
_sym_db.RegisterEnumDescriptor(_CARRIERCARDDATAREQUEST_REQUESTTYPET)

_ERRORMSG_ERRCODE = _descriptor.EnumDescriptor(
  name='ErrCode',
  full_name='mpsqual.ErrorMsg.ErrCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FAILURE_INVALID_MESSAGE', index=0, number=1000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE_INVALID_KEY', index=1, number=1001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE_INVALID_VALUE', index=2, number=1002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE_WRITE_PROTECT_DISABLED', index=3, number=1003,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE_READ_FAILED', index=4, number=1004,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE_WRITE_FAILED', index=5, number=1005,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=463,
  serialized_end=646,
)
_sym_db.RegisterEnumDescriptor(_ERRORMSG_ERRCODE)


_CARRIERCARDDATAREQUEST = _descriptor.Descriptor(
  name='CarrierCardDataRequest',
  full_name='mpsqual.CarrierCardDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.CarrierCardDataRequest.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='mpsqual.CarrierCardDataRequest.values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CARRIERCARDDATAREQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=228,
)


_CARRIERCARDDATARESPONSE = _descriptor.Descriptor(
  name='CarrierCardDataResponse',
  full_name='mpsqual.CarrierCardDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='mpsqual.CarrierCardDataResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='mpsqual.CarrierCardDataResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='writeProtected', full_name='mpsqual.CarrierCardDataResponse.writeProtected', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='mpsqual.CarrierCardDataResponse.values', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=366,
)


_PROPERTY = _descriptor.Descriptor(
  name='Property',
  full_name='mpsqual.Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mpsqual.Property.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='mpsqual.Property.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=406,
)


_ERRORMSG = _descriptor.Descriptor(
  name='ErrorMsg',
  full_name='mpsqual.ErrorMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='mpsqual.ErrorMsg.error_code', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='mpsqual.ErrorMsg.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ERRORMSG_ERRCODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=646,
)

_CARRIERCARDDATAREQUEST.fields_by_name['requestType'].enum_type = _CARRIERCARDDATAREQUEST_REQUESTTYPET
_CARRIERCARDDATAREQUEST.fields_by_name['values'].message_type = _PROPERTY
_CARRIERCARDDATAREQUEST_REQUESTTYPET.containing_type = _CARRIERCARDDATAREQUEST
_CARRIERCARDDATARESPONSE.fields_by_name['error'].message_type = _ERRORMSG
_CARRIERCARDDATARESPONSE.fields_by_name['values'].message_type = _PROPERTY
_ERRORMSG_ERRCODE.containing_type = _ERRORMSG
DESCRIPTOR.message_types_by_name['CarrierCardDataRequest'] = _CARRIERCARDDATAREQUEST
DESCRIPTOR.message_types_by_name['CarrierCardDataResponse'] = _CARRIERCARDDATARESPONSE
DESCRIPTOR.message_types_by_name['Property'] = _PROPERTY
DESCRIPTOR.message_types_by_name['ErrorMsg'] = _ERRORMSG

CarrierCardDataRequest = _reflection.GeneratedProtocolMessageType('CarrierCardDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _CARRIERCARDDATAREQUEST,
  __module__ = 'CarrierCardData_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.CarrierCardDataRequest)
  ))
_sym_db.RegisterMessage(CarrierCardDataRequest)

CarrierCardDataResponse = _reflection.GeneratedProtocolMessageType('CarrierCardDataResponse', (_message.Message,), dict(
  DESCRIPTOR = _CARRIERCARDDATARESPONSE,
  __module__ = 'CarrierCardData_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.CarrierCardDataResponse)
  ))
_sym_db.RegisterMessage(CarrierCardDataResponse)

Property = _reflection.GeneratedProtocolMessageType('Property', (_message.Message,), dict(
  DESCRIPTOR = _PROPERTY,
  __module__ = 'CarrierCardData_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.Property)
  ))
_sym_db.RegisterMessage(Property)

ErrorMsg = _reflection.GeneratedProtocolMessageType('ErrorMsg', (_message.Message,), dict(
  DESCRIPTOR = _ERRORMSG,
  __module__ = 'CarrierCardData_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.ErrorMsg)
  ))
_sym_db.RegisterMessage(ErrorMsg)


# @@protoc_insertion_point(module_scope)
