# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HDAudio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HDAudio.proto',
  package='mpsqual',
  serialized_pb=_b('\n\rHDAudio.proto\x12\x07mpsqual\"\xb2\x01\n\x0eHDAudioRequest\x12\x45\n\x0brequestType\x18\x01 \x02(\x0e\x32$.mpsqual.HDAudioRequest.RequestTypeT:\nDISCONNECT\x12\x10\n\x06source\x18\x02 \x01(\t:\x00\x12\x0e\n\x06volume\x18\x03 \x01(\x02\"7\n\x0cRequestTypeT\x12\x0e\n\nDISCONNECT\x10\x00\x12\x0b\n\x07\x43ONNECT\x10\x01\x12\n\n\x06REPORT\x10\x02\"\xa5\x01\n\x0fHDAudioResponse\x12\x42\n\x08\x61ppState\x18\x01 \x02(\x0e\x32\".mpsqual.HDAudioResponse.AppStateT:\x0c\x44ISCONNECTED\x12\x10\n\x06source\x18\x02 \x02(\t:\x00\x12\x0e\n\x06volume\x18\x03 \x02(\x02\",\n\tAppStateT\x12\x10\n\x0c\x44ISCONNECTED\x10\x00\x12\r\n\tCONNECTED\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_HDAUDIOREQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.HDAudioRequest.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=150,
  serialized_end=205,
)
_sym_db.RegisterEnumDescriptor(_HDAUDIOREQUEST_REQUESTTYPET)

_HDAUDIORESPONSE_APPSTATET = _descriptor.EnumDescriptor(
  name='AppStateT',
  full_name='mpsqual.HDAudioResponse.AppStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=329,
  serialized_end=373,
)
_sym_db.RegisterEnumDescriptor(_HDAUDIORESPONSE_APPSTATET)


_HDAUDIOREQUEST = _descriptor.Descriptor(
  name='HDAudioRequest',
  full_name='mpsqual.HDAudioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.HDAudioRequest.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='mpsqual.HDAudioRequest.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume', full_name='mpsqual.HDAudioRequest.volume', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HDAUDIOREQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=205,
)


_HDAUDIORESPONSE = _descriptor.Descriptor(
  name='HDAudioResponse',
  full_name='mpsqual.HDAudioResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appState', full_name='mpsqual.HDAudioResponse.appState', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='mpsqual.HDAudioResponse.source', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume', full_name='mpsqual.HDAudioResponse.volume', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HDAUDIORESPONSE_APPSTATET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=373,
)

_HDAUDIOREQUEST.fields_by_name['requestType'].enum_type = _HDAUDIOREQUEST_REQUESTTYPET
_HDAUDIOREQUEST_REQUESTTYPET.containing_type = _HDAUDIOREQUEST
_HDAUDIORESPONSE.fields_by_name['appState'].enum_type = _HDAUDIORESPONSE_APPSTATET
_HDAUDIORESPONSE_APPSTATET.containing_type = _HDAUDIORESPONSE
DESCRIPTOR.message_types_by_name['HDAudioRequest'] = _HDAUDIOREQUEST
DESCRIPTOR.message_types_by_name['HDAudioResponse'] = _HDAUDIORESPONSE

HDAudioRequest = _reflection.GeneratedProtocolMessageType('HDAudioRequest', (_message.Message,), dict(
  DESCRIPTOR = _HDAUDIOREQUEST,
  __module__ = 'HDAudio_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.HDAudioRequest)
  ))
_sym_db.RegisterMessage(HDAudioRequest)

HDAudioResponse = _reflection.GeneratedProtocolMessageType('HDAudioResponse', (_message.Message,), dict(
  DESCRIPTOR = _HDAUDIORESPONSE,
  __module__ = 'HDAudio_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.HDAudioResponse)
  ))
_sym_db.RegisterMessage(HDAudioResponse)


# @@protoc_insertion_point(module_scope)
