# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RTC.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RTC.proto',
  package='mpsqual',
  serialized_pb=_b('\n\tRTC.proto\x12\x07mpsqual\"\xb9\x01\n\nRTCRequest\x12\x34\n\x0brequestType\x18\x01 \x02(\x0e\x32\x1f.mpsqual.RTCRequest.RTCRequestT\x12\x12\n\ntimeString\x18\x02 \x01(\t\"a\n\x0bRTCRequestT\x12\x0b\n\x07RTC_GET\x10\x00\x12\x0b\n\x07RTC_SET\x10\x01\x12\x12\n\x0eRTC_SYSTEM_SET\x10\x02\x12\x11\n\rRTC_TO_SYSTEM\x10\x03\x12\x11\n\rSYSTEM_TO_RTC\x10\x04\"2\n\x0bRTCResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x12\n\ntimeString\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RTCREQUEST_RTCREQUESTT = _descriptor.EnumDescriptor(
  name='RTCRequestT',
  full_name='mpsqual.RTCRequest.RTCRequestT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RTC_GET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RTC_SET', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RTC_SYSTEM_SET', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RTC_TO_SYSTEM', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYSTEM_TO_RTC', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=111,
  serialized_end=208,
)
_sym_db.RegisterEnumDescriptor(_RTCREQUEST_RTCREQUESTT)


_RTCREQUEST = _descriptor.Descriptor(
  name='RTCRequest',
  full_name='mpsqual.RTCRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.RTCRequest.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeString', full_name='mpsqual.RTCRequest.timeString', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RTCREQUEST_RTCREQUESTT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=208,
)


_RTCRESPONSE = _descriptor.Descriptor(
  name='RTCResponse',
  full_name='mpsqual.RTCResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='mpsqual.RTCResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeString', full_name='mpsqual.RTCResponse.timeString', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=260,
)

_RTCREQUEST.fields_by_name['requestType'].enum_type = _RTCREQUEST_RTCREQUESTT
_RTCREQUEST_RTCREQUESTT.containing_type = _RTCREQUEST
DESCRIPTOR.message_types_by_name['RTCRequest'] = _RTCREQUEST
DESCRIPTOR.message_types_by_name['RTCResponse'] = _RTCRESPONSE

RTCRequest = _reflection.GeneratedProtocolMessageType('RTCRequest', (_message.Message,), dict(
  DESCRIPTOR = _RTCREQUEST,
  __module__ = 'RTC_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.RTCRequest)
  ))
_sym_db.RegisterMessage(RTCRequest)

RTCResponse = _reflection.GeneratedProtocolMessageType('RTCResponse', (_message.Message,), dict(
  DESCRIPTOR = _RTCRESPONSE,
  __module__ = 'RTC_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.RTCResponse)
  ))
_sym_db.RegisterMessage(RTCResponse)


# @@protoc_insertion_point(module_scope)
