# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SSDErase.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SSDErase.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x0eSSDErase.proto\x12\x07mpsqual\" \n\x0fSSDEraseRequest\x12\r\n\x05\x65rase\x18\x01 \x02(\x08\";\n\x10SSDEraseResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x16\n\x0c\x65rrorMessage\x18\x02 \x01(\t:\x00')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SSDERASEREQUEST = _descriptor.Descriptor(
  name='SSDEraseRequest',
  full_name='mpsqual.SSDEraseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='erase', full_name='mpsqual.SSDEraseRequest.erase', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=59,
)


_SSDERASERESPONSE = _descriptor.Descriptor(
  name='SSDEraseResponse',
  full_name='mpsqual.SSDEraseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='mpsqual.SSDEraseResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorMessage', full_name='mpsqual.SSDEraseResponse.errorMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['SSDEraseRequest'] = _SSDERASEREQUEST
DESCRIPTOR.message_types_by_name['SSDEraseResponse'] = _SSDERASERESPONSE

SSDEraseRequest = _reflection.GeneratedProtocolMessageType('SSDEraseRequest', (_message.Message,), dict(
  DESCRIPTOR = _SSDERASEREQUEST,
  __module__ = 'SSDErase_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.SSDEraseRequest)
  ))
_sym_db.RegisterMessage(SSDEraseRequest)

SSDEraseResponse = _reflection.GeneratedProtocolMessageType('SSDEraseResponse', (_message.Message,), dict(
  DESCRIPTOR = _SSDERASERESPONSE,
  __module__ = 'SSDErase_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.SSDEraseResponse)
  ))
_sym_db.RegisterMessage(SSDEraseResponse)


# @@protoc_insertion_point(module_scope)
