# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ErrorMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ErrorMessage.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x12\x45rrorMessage.proto\x12\x07mpsqual\"=\n\x0c\x45rrorMessage\x12\x12\n\nerror_code\x18\x01 \x02(\r\x12\x19\n\x11\x65rror_description\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ERRORMESSAGE = _descriptor.Descriptor(
  name='ErrorMessage',
  full_name='mpsqual.ErrorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='mpsqual.ErrorMessage.error_code', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_description', full_name='mpsqual.ErrorMessage.error_description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['ErrorMessage'] = _ERRORMESSAGE

ErrorMessage = _reflection.GeneratedProtocolMessageType('ErrorMessage', (_message.Message,), dict(
  DESCRIPTOR = _ERRORMESSAGE,
  __module__ = 'ErrorMessage_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.ErrorMessage)
  ))
_sym_db.RegisterMessage(ErrorMessage)


# @@protoc_insertion_point(module_scope)
