# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GPIOManager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GPIOManager.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x11GPIOManager.proto\x12\x07mpsqual\"\xc6\x01\n\x0eRequestMessage\x12\x10\n\x08pin_name\x18\x01 \x02(\t\x12?\n\x0crequest_type\x18\x02 \x02(\x0e\x32$.mpsqual.RequestMessage.RequestTypeT:\x03GET\x12\x14\n\x05value\x18\x03 \x01(\x08:\x05\x66\x61lse\x12)\n\tdirection\x18\x04 \x01(\x0e\x32\x16.mpsqual.GpioDirection\" \n\x0cRequestTypeT\x12\x07\n\x03GET\x10\x00\x12\x07\n\x03SET\x10\x01\"\xf8\x02\n\x0fResponseMessage\x12\x10\n\x08pin_name\x18\x01 \x02(\t\x12\x14\n\x05state\x18\x02 \x02(\x08:\x05\x66\x61lse\x12\x30\n\tdirection\x18\x03 \x02(\x0e\x32\x16.mpsqual.GpioDirection:\x05INPUT\x12\x39\n\x05\x65rror\x18\x04 \x02(\x0e\x32&.mpsqual.ResponseMessage.ErrStatusCode:\x02OK\"\xcf\x01\n\rErrStatusCode\x12\x06\n\x02OK\x10\x00\x12\x15\n\x11IMPROPER_PIN_NAME\x10\x01\x12\x18\n\x14IMPROPER_STATE_VALUE\x10\x02\x12\x19\n\x15IMPROPER_REQUEST_TYPE\x10\x03\x12\x14\n\x10IMPROPER_MESSAGE\x10\x04\x12\x17\n\x13\x44IRECTION_SET_ERROR\x10\x05\x12\x15\n\x11SET_INPUT_PIN_ERR\x10\x06\x12\x13\n\x0fGPIO_DRIVER_ERR\x10\x07\x12\x0f\n\x0bUNKNOWN_ERR\x10\x08*7\n\rGpioDirection\x12\x0f\n\x0bUNKNOWN_DIR\x10\x02\x12\t\n\x05INPUT\x10\x00\x12\n\n\x06OUTPUT\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_GPIODIRECTION = _descriptor.EnumDescriptor(
  name='GpioDirection',
  full_name='mpsqual.GpioDirection',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_DIR', index=0, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INPUT', index=1, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUTPUT', index=2, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=610,
  serialized_end=665,
)
_sym_db.RegisterEnumDescriptor(_GPIODIRECTION)

GpioDirection = enum_type_wrapper.EnumTypeWrapper(_GPIODIRECTION)
UNKNOWN_DIR = 2
INPUT = 0
OUTPUT = 1


_REQUESTMESSAGE_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.RequestMessage.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=197,
  serialized_end=229,
)
_sym_db.RegisterEnumDescriptor(_REQUESTMESSAGE_REQUESTTYPET)

_RESPONSEMESSAGE_ERRSTATUSCODE = _descriptor.EnumDescriptor(
  name='ErrStatusCode',
  full_name='mpsqual.ResponseMessage.ErrStatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMPROPER_PIN_NAME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMPROPER_STATE_VALUE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMPROPER_REQUEST_TYPE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMPROPER_MESSAGE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIRECTION_SET_ERROR', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_INPUT_PIN_ERR', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPIO_DRIVER_ERR', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ERR', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=401,
  serialized_end=608,
)
_sym_db.RegisterEnumDescriptor(_RESPONSEMESSAGE_ERRSTATUSCODE)


_REQUESTMESSAGE = _descriptor.Descriptor(
  name='RequestMessage',
  full_name='mpsqual.RequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pin_name', full_name='mpsqual.RequestMessage.pin_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_type', full_name='mpsqual.RequestMessage.request_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='mpsqual.RequestMessage.value', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direction', full_name='mpsqual.RequestMessage.direction', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTMESSAGE_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=229,
)


_RESPONSEMESSAGE = _descriptor.Descriptor(
  name='ResponseMessage',
  full_name='mpsqual.ResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pin_name', full_name='mpsqual.ResponseMessage.pin_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='mpsqual.ResponseMessage.state', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direction', full_name='mpsqual.ResponseMessage.direction', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='mpsqual.ResponseMessage.error', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSEMESSAGE_ERRSTATUSCODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=608,
)

_REQUESTMESSAGE.fields_by_name['request_type'].enum_type = _REQUESTMESSAGE_REQUESTTYPET
_REQUESTMESSAGE.fields_by_name['direction'].enum_type = _GPIODIRECTION
_REQUESTMESSAGE_REQUESTTYPET.containing_type = _REQUESTMESSAGE
_RESPONSEMESSAGE.fields_by_name['direction'].enum_type = _GPIODIRECTION
_RESPONSEMESSAGE.fields_by_name['error'].enum_type = _RESPONSEMESSAGE_ERRSTATUSCODE
_RESPONSEMESSAGE_ERRSTATUSCODE.containing_type = _RESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['RequestMessage'] = _REQUESTMESSAGE
DESCRIPTOR.message_types_by_name['ResponseMessage'] = _RESPONSEMESSAGE
DESCRIPTOR.enum_types_by_name['GpioDirection'] = _GPIODIRECTION

RequestMessage = _reflection.GeneratedProtocolMessageType('RequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTMESSAGE,
  __module__ = 'GPIOManager_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.RequestMessage)
  ))
_sym_db.RegisterMessage(RequestMessage)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEMESSAGE,
  __module__ = 'GPIOManager_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.ResponseMessage)
  ))
_sym_db.RegisterMessage(ResponseMessage)


# @@protoc_insertion_point(module_scope)
