# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PowerInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PowerInfo.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x0fPowerInfo.proto\x12\x07mpsqual\")\n\x0cGetPowerInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"8\n\x0cSetPowerInfo\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03key\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x02(\t\"\xf4\x01\n\tPowerInfo\x12+\n\terrorCode\x18\x01 \x02(\x0e\x32\x18.mpsqual.PowerInfo.Error\x12\x1e\n\x06values\x18\x02 \x03(\x0b\x32\x0e.mpsqual.Value\"\x99\x01\n\x05\x45rror\x12\x0b\n\x07SUCCESS\x10\x00\x12\x13\n\x0fINVALID_MESSAGE\x10\x01\x12\x17\n\x13INVALID_DEVICE_NAME\x10\x02\x12\x0f\n\x0bINVALID_KEY\x10\x03\x12\x16\n\x12I2C_MGR_CONN_ERROR\x10\x04\x12\x17\n\x13GPIO_MGR_CONN_ERROR\x10\x05\x12\x13\n\x0fOPERATION_ERROR\x10\x06\"1\n\x05Value\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03key\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_POWERINFO_ERROR = _descriptor.EnumDescriptor(
  name='Error',
  full_name='mpsqual.PowerInfo.Error',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_MESSAGE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_DEVICE_NAME', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_KEY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='I2C_MGR_CONN_ERROR', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GPIO_MGR_CONN_ERROR', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPERATION_ERROR', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=221,
  serialized_end=374,
)
_sym_db.RegisterEnumDescriptor(_POWERINFO_ERROR)


_GETPOWERINFO = _descriptor.Descriptor(
  name='GetPowerInfo',
  full_name='mpsqual.GetPowerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mpsqual.GetPowerInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='mpsqual.GetPowerInfo.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=69,
)


_SETPOWERINFO = _descriptor.Descriptor(
  name='SetPowerInfo',
  full_name='mpsqual.SetPowerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mpsqual.SetPowerInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='mpsqual.SetPowerInfo.key', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='mpsqual.SetPowerInfo.value', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=127,
)


_POWERINFO = _descriptor.Descriptor(
  name='PowerInfo',
  full_name='mpsqual.PowerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='mpsqual.PowerInfo.errorCode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='mpsqual.PowerInfo.values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POWERINFO_ERROR,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=374,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='mpsqual.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mpsqual.Value.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='mpsqual.Value.key', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='mpsqual.Value.value', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=425,
)

_POWERINFO.fields_by_name['errorCode'].enum_type = _POWERINFO_ERROR
_POWERINFO.fields_by_name['values'].message_type = _VALUE
_POWERINFO_ERROR.containing_type = _POWERINFO
DESCRIPTOR.message_types_by_name['GetPowerInfo'] = _GETPOWERINFO
DESCRIPTOR.message_types_by_name['SetPowerInfo'] = _SETPOWERINFO
DESCRIPTOR.message_types_by_name['PowerInfo'] = _POWERINFO
DESCRIPTOR.message_types_by_name['Value'] = _VALUE

GetPowerInfo = _reflection.GeneratedProtocolMessageType('GetPowerInfo', (_message.Message,), dict(
  DESCRIPTOR = _GETPOWERINFO,
  __module__ = 'PowerInfo_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.GetPowerInfo)
  ))
_sym_db.RegisterMessage(GetPowerInfo)

SetPowerInfo = _reflection.GeneratedProtocolMessageType('SetPowerInfo', (_message.Message,), dict(
  DESCRIPTOR = _SETPOWERINFO,
  __module__ = 'PowerInfo_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.SetPowerInfo)
  ))
_sym_db.RegisterMessage(SetPowerInfo)

PowerInfo = _reflection.GeneratedProtocolMessageType('PowerInfo', (_message.Message,), dict(
  DESCRIPTOR = _POWERINFO,
  __module__ = 'PowerInfo_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.PowerInfo)
  ))
_sym_db.RegisterMessage(PowerInfo)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'PowerInfo_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.Value)
  ))
_sym_db.RegisterMessage(Value)


# @@protoc_insertion_point(module_scope)
