# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rtc_driver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rtc_driver.proto',
  package='',
  serialized_pb=_b('\n\x10rtc_driver.proto\"\t\n\x07GetTime\"\x1b\n\x07SetTime\x12\x10\n\x08\x64\x61tetime\x18\x02 \x02(\t\"7\n\x0cTimeResponse\x12\x15\n\x05\x65rror\x18\x01 \x02(\x0e\x32\x06.Error\x12\x10\n\x08\x64\x61tetime\x18\x02 \x01(\t*|\n\x05\x45rror\x12\x0b\n\x07SUCCESS\x10\x00\x12\x13\n\x0fINVALID_MESSAGE\x10\x01\x12\x15\n\x11INVALID_OPERATION\x10\x02\x12\x17\n\x13INVALID_SET_REQUEST\x10\x03\x12\x12\n\x0eSPI_CONN_ERROR\x10\x04\x12\r\n\tRTC_ERROR\x10\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ERROR = _descriptor.EnumDescriptor(
  name='Error',
  full_name='Error',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_MESSAGE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_OPERATION', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_SET_REQUEST', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPI_CONN_ERROR', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RTC_ERROR', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=117,
  serialized_end=241,
)
_sym_db.RegisterEnumDescriptor(_ERROR)

Error = enum_type_wrapper.EnumTypeWrapper(_ERROR)
SUCCESS = 0
INVALID_MESSAGE = 1
INVALID_OPERATION = 2
INVALID_SET_REQUEST = 3
SPI_CONN_ERROR = 4
RTC_ERROR = 5



_GETTIME = _descriptor.Descriptor(
  name='GetTime',
  full_name='GetTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=29,
)


_SETTIME = _descriptor.Descriptor(
  name='SetTime',
  full_name='SetTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datetime', full_name='SetTime.datetime', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=58,
)


_TIMERESPONSE = _descriptor.Descriptor(
  name='TimeResponse',
  full_name='TimeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='TimeResponse.error', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='TimeResponse.datetime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=115,
)

_TIMERESPONSE.fields_by_name['error'].enum_type = _ERROR
DESCRIPTOR.message_types_by_name['GetTime'] = _GETTIME
DESCRIPTOR.message_types_by_name['SetTime'] = _SETTIME
DESCRIPTOR.message_types_by_name['TimeResponse'] = _TIMERESPONSE
DESCRIPTOR.enum_types_by_name['Error'] = _ERROR

GetTime = _reflection.GeneratedProtocolMessageType('GetTime', (_message.Message,), dict(
  DESCRIPTOR = _GETTIME,
  __module__ = 'rtc_driver_pb2'
  # @@protoc_insertion_point(class_scope:GetTime)
  ))
_sym_db.RegisterMessage(GetTime)

SetTime = _reflection.GeneratedProtocolMessageType('SetTime', (_message.Message,), dict(
  DESCRIPTOR = _SETTIME,
  __module__ = 'rtc_driver_pb2'
  # @@protoc_insertion_point(class_scope:SetTime)
  ))
_sym_db.RegisterMessage(SetTime)

TimeResponse = _reflection.GeneratedProtocolMessageType('TimeResponse', (_message.Message,), dict(
  DESCRIPTOR = _TIMERESPONSE,
  __module__ = 'rtc_driver_pb2'
  # @@protoc_insertion_point(class_scope:TimeResponse)
  ))
_sym_db.RegisterMessage(TimeResponse)


# @@protoc_insertion_point(module_scope)
