import os
from common.gpb.python.ARINC717Frame_pb2 import ARINC717FrameRequest, ARINC717FrameResponse
from common.tzmq.ThalesZMQClient import ThalesZMQClient
from common.tzmq.ThalesZMQMessage import ThalesZMQMessage
from common.gpb.python.ARINC717Driver_pb2 import Request, Response
from common.module.module import Module

## ARINC717 Module
class ARINC717(Module):
    ## Constructor
    #  @param   self
    #  @param   config  Configuration for this module instance
    def __init__(self, config =None):
        #  Initialize parent class
        super(ARINC717, self).__init__(config)

        #  Ensure directory for communication with ARINC717 driver is present
        ipcdir = "/tmp/arinc/driver/717"
        if not os.path.exists(ipcdir):
            os.makedirs(ipcdir)

        ## Connection to ARINC717 driver
        self.driverClient = ThalesZMQClient("ipc:///tmp/arinc/driver/717/device")
        #  Add handler to available message handlers
        self.addMsgHandler(ARINC717FrameRequest, self.handler)

    ## Sends RECEIVE_FRAME request message to the ARINC717 driver
    #  @param     self
    #  @return    a ThalesZMQMessage object returned from the ARINC717 driver
    def makeRequest(self):
        request = Request()
        request.type = Request.RECEIVE_FRAME

        return self.driverClient.sendRequest(ThalesZMQMessage(request))

    ## Handles incoming messages
    #  Receives TZMQ request and performs requested action
    #  @param     self
    #  @param     msg       TZMQ format message
    #  @return    a ThalesZMQMessage object containing the response message
    def handler(self, msg):
        response = ARINC717FrameResponse()
        response.state = ARINC717FrameResponse.RUNNING

        if msg.body.requestType == ARINC717FrameRequest.RUN:
            self.start(response)
        elif msg.body.requestType == ARINC717FrameRequest.STOP:
            self.stop(response)
        elif msg.body.requestType == ARINC717FrameRequest.REPORT:
            self.report(response)
        else:
            self.log.error("Unexpected Request Type %d" % (msg.body.requestType))

        return ThalesZMQMessage(response)

    ## Handles messages with requestType of RUN
    #  RUN request type is defined in the ICD, but is not applicable to
    #  this module, so we just behave the same as REPORT.
    #  @param     self
    #  @return    an ARINC717FrameResponse object generated by report() function
    def start(self, response):
        self.report(response)

    ## Handles messages with requestType of STOP
    #  STOP request type is defined in the ICD, but is not applicable to
    #  this module, so we just behave the same as REPORT.
    #  @param     self
    #  @return    an ARINC717FrameResponse object generated by report() function
    def stop(self, response):
        self.report(response)

    ## Handles messages with requestType of REPORT
    #  @param     self
    #  @return    an ARINC717FrameResponse object containing frame status and data
    def report(self, response):
        info = Response()
        info.ParseFromString(self.makeRequest().serializedBody)
        data = info.frame.data
        response.syncState = info.frame.out_of_sync

        #  turns every two characters in data into 16-bit data
        for char in range(0, len(data), 2):
            response.arinc717frame.append((ord(data[char]) << 8) | ord(data[char + 1]))