# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AnalogAudio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AnalogAudio.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x11\x41nalogAudio.proto\x12\x07mpsqual\"\xbd\x01\n\x12\x41nalogAudioRequest\x12I\n\x0brequestType\x18\x01 \x02(\x0e\x32(.mpsqual.AnalogAudioRequest.RequestTypeT:\nDISCONNECT\x12\x11\n\x04sink\x18\x02 \x02(\t:\x03\x41LL\x12\x10\n\x06source\x18\x03 \x01(\t:\x00\"7\n\x0cRequestTypeT\x12\x0e\n\nDISCONNECT\x10\x00\x12\x0b\n\x07\x43ONNECT\x10\x01\x12\n\n\x06REPORT\x10\x02\"\x83\x02\n\x13\x41nalogAudioResponse\x12;\n\x08loopback\x18\x01 \x03(\x0b\x32).mpsqual.AnalogAudioResponse.OutputStatus\x1az\n\x0cOutputStatus\x12\x0c\n\x04sink\x18\x01 \x02(\t\x12\x10\n\x06source\x18\x02 \x02(\t:\x00\x12J\n\x05state\x18\x03 \x02(\x0e\x32-.mpsqual.AnalogAudioResponse.ConnectionStateT:\x0c\x44ISCONNECTED\"3\n\x10\x43onnectionStateT\x12\x10\n\x0c\x44ISCONNECTED\x10\x00\x12\r\n\tCONNECTED\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ANALOGAUDIOREQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.AnalogAudioRequest.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=165,
  serialized_end=220,
)
_sym_db.RegisterEnumDescriptor(_ANALOGAUDIOREQUEST_REQUESTTYPET)

_ANALOGAUDIORESPONSE_CONNECTIONSTATET = _descriptor.EnumDescriptor(
  name='ConnectionStateT',
  full_name='mpsqual.AnalogAudioResponse.ConnectionStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=431,
  serialized_end=482,
)
_sym_db.RegisterEnumDescriptor(_ANALOGAUDIORESPONSE_CONNECTIONSTATET)


_ANALOGAUDIOREQUEST = _descriptor.Descriptor(
  name='AnalogAudioRequest',
  full_name='mpsqual.AnalogAudioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.AnalogAudioRequest.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sink', full_name='mpsqual.AnalogAudioRequest.sink', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("ALL").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='mpsqual.AnalogAudioRequest.source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ANALOGAUDIOREQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=220,
)


_ANALOGAUDIORESPONSE_OUTPUTSTATUS = _descriptor.Descriptor(
  name='OutputStatus',
  full_name='mpsqual.AnalogAudioResponse.OutputStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sink', full_name='mpsqual.AnalogAudioResponse.OutputStatus.sink', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='mpsqual.AnalogAudioResponse.OutputStatus.source', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='mpsqual.AnalogAudioResponse.OutputStatus.state', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=429,
)

_ANALOGAUDIORESPONSE = _descriptor.Descriptor(
  name='AnalogAudioResponse',
  full_name='mpsqual.AnalogAudioResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loopback', full_name='mpsqual.AnalogAudioResponse.loopback', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ANALOGAUDIORESPONSE_OUTPUTSTATUS, ],
  enum_types=[
    _ANALOGAUDIORESPONSE_CONNECTIONSTATET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=482,
)

_ANALOGAUDIOREQUEST.fields_by_name['requestType'].enum_type = _ANALOGAUDIOREQUEST_REQUESTTYPET
_ANALOGAUDIOREQUEST_REQUESTTYPET.containing_type = _ANALOGAUDIOREQUEST
_ANALOGAUDIORESPONSE_OUTPUTSTATUS.fields_by_name['state'].enum_type = _ANALOGAUDIORESPONSE_CONNECTIONSTATET
_ANALOGAUDIORESPONSE_OUTPUTSTATUS.containing_type = _ANALOGAUDIORESPONSE
_ANALOGAUDIORESPONSE.fields_by_name['loopback'].message_type = _ANALOGAUDIORESPONSE_OUTPUTSTATUS
_ANALOGAUDIORESPONSE_CONNECTIONSTATET.containing_type = _ANALOGAUDIORESPONSE
DESCRIPTOR.message_types_by_name['AnalogAudioRequest'] = _ANALOGAUDIOREQUEST
DESCRIPTOR.message_types_by_name['AnalogAudioResponse'] = _ANALOGAUDIORESPONSE

AnalogAudioRequest = _reflection.GeneratedProtocolMessageType('AnalogAudioRequest', (_message.Message,), dict(
  DESCRIPTOR = _ANALOGAUDIOREQUEST,
  __module__ = 'AnalogAudio_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.AnalogAudioRequest)
  ))
_sym_db.RegisterMessage(AnalogAudioRequest)

AnalogAudioResponse = _reflection.GeneratedProtocolMessageType('AnalogAudioResponse', (_message.Message,), dict(

  OutputStatus = _reflection.GeneratedProtocolMessageType('OutputStatus', (_message.Message,), dict(
    DESCRIPTOR = _ANALOGAUDIORESPONSE_OUTPUTSTATUS,
    __module__ = 'AnalogAudio_pb2'
    # @@protoc_insertion_point(class_scope:mpsqual.AnalogAudioResponse.OutputStatus)
    ))
  ,
  DESCRIPTOR = _ANALOGAUDIORESPONSE,
  __module__ = 'AnalogAudio_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.AnalogAudioResponse)
  ))
_sym_db.RegisterMessage(AnalogAudioResponse)
_sym_db.RegisterMessage(AnalogAudioResponse.OutputStatus)


# @@protoc_insertion_point(module_scope)
