# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CPULoading.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CPULoading.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x10\x43PULoading.proto\x12\x07mpsqual\"\x95\x01\n\x11\x43PULoadingRequest\x12\x42\n\x0brequestType\x18\x01 \x02(\x0e\x32\'.mpsqual.CPULoadingRequest.RequestTypeT:\x04STOP\x12\r\n\x05level\x18\x02 \x01(\x02\"-\n\x0cRequestTypeT\x12\x08\n\x04STOP\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\n\n\x06REPORT\x10\x02\"\xa4\x01\n\x12\x43PULoadingResponse\x12\x34\n\x05state\x18\x01 \x02(\x0e\x32%.mpsqual.CPULoadingResponse.AppStateT\x12\x18\n\x10totalUtilization\x18\x02 \x02(\x02\x12\x17\n\x0f\x63oreUtilization\x18\x03 \x03(\x02\"%\n\tAppStateT\x12\x0b\n\x07STOPPED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CPULOADINGREQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.CPULoadingRequest.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=134,
  serialized_end=179,
)
_sym_db.RegisterEnumDescriptor(_CPULOADINGREQUEST_REQUESTTYPET)

_CPULOADINGRESPONSE_APPSTATET = _descriptor.EnumDescriptor(
  name='AppStateT',
  full_name='mpsqual.CPULoadingResponse.AppStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=309,
  serialized_end=346,
)
_sym_db.RegisterEnumDescriptor(_CPULOADINGRESPONSE_APPSTATET)


_CPULOADINGREQUEST = _descriptor.Descriptor(
  name='CPULoadingRequest',
  full_name='mpsqual.CPULoadingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.CPULoadingRequest.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='mpsqual.CPULoadingRequest.level', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CPULOADINGREQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=179,
)


_CPULOADINGRESPONSE = _descriptor.Descriptor(
  name='CPULoadingResponse',
  full_name='mpsqual.CPULoadingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='mpsqual.CPULoadingResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalUtilization', full_name='mpsqual.CPULoadingResponse.totalUtilization', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coreUtilization', full_name='mpsqual.CPULoadingResponse.coreUtilization', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CPULOADINGRESPONSE_APPSTATET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=346,
)

_CPULOADINGREQUEST.fields_by_name['requestType'].enum_type = _CPULOADINGREQUEST_REQUESTTYPET
_CPULOADINGREQUEST_REQUESTTYPET.containing_type = _CPULOADINGREQUEST
_CPULOADINGRESPONSE.fields_by_name['state'].enum_type = _CPULOADINGRESPONSE_APPSTATET
_CPULOADINGRESPONSE_APPSTATET.containing_type = _CPULOADINGRESPONSE
DESCRIPTOR.message_types_by_name['CPULoadingRequest'] = _CPULOADINGREQUEST
DESCRIPTOR.message_types_by_name['CPULoadingResponse'] = _CPULOADINGRESPONSE

CPULoadingRequest = _reflection.GeneratedProtocolMessageType('CPULoadingRequest', (_message.Message,), dict(
  DESCRIPTOR = _CPULOADINGREQUEST,
  __module__ = 'CPULoading_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.CPULoadingRequest)
  ))
_sym_db.RegisterMessage(CPULoadingRequest)

CPULoadingResponse = _reflection.GeneratedProtocolMessageType('CPULoadingResponse', (_message.Message,), dict(
  DESCRIPTOR = _CPULOADINGRESPONSE,
  __module__ = 'CPULoading_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.CPULoadingResponse)
  ))
_sym_db.RegisterMessage(CPULoadingResponse)


# @@protoc_insertion_point(module_scope)
