# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Encoder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Encoder.proto',
  package='mpsqual',
  serialized_pb=_b('\n\rEncoder.proto\x12\x07mpsqual\"\x8e\x01\n\x0e\x45ncoderRequest\x12?\n\x0brequestType\x18\x01 \x02(\x0e\x32$.mpsqual.EncoderRequest.RequestTypeT:\x04STOP\x12\x0c\n\x04sink\x18\x02 \x01(\t\"-\n\x0cRequestTypeT\x12\x08\n\x04STOP\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\n\n\x06REPORT\x10\x02\"\x88\x01\n\x0f\x45ncoderResponse\x12\x31\n\x05state\x18\x01 \x02(\x0e\x32\".mpsqual.EncoderResponse.AppStateT\x12\x1b\n\x0cstreamActive\x18\x03 \x02(\x08:\x05\x66\x61lse\"%\n\tAppStateT\x12\x0b\n\x07STOPPED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ENCODERREQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.EncoderRequest.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=124,
  serialized_end=169,
)
_sym_db.RegisterEnumDescriptor(_ENCODERREQUEST_REQUESTTYPET)

_ENCODERRESPONSE_APPSTATET = _descriptor.EnumDescriptor(
  name='AppStateT',
  full_name='mpsqual.EncoderResponse.AppStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=271,
  serialized_end=308,
)
_sym_db.RegisterEnumDescriptor(_ENCODERRESPONSE_APPSTATET)


_ENCODERREQUEST = _descriptor.Descriptor(
  name='EncoderRequest',
  full_name='mpsqual.EncoderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.EncoderRequest.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sink', full_name='mpsqual.EncoderRequest.sink', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENCODERREQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=169,
)


_ENCODERRESPONSE = _descriptor.Descriptor(
  name='EncoderResponse',
  full_name='mpsqual.EncoderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='mpsqual.EncoderResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='streamActive', full_name='mpsqual.EncoderResponse.streamActive', index=1,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENCODERRESPONSE_APPSTATET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=308,
)

_ENCODERREQUEST.fields_by_name['requestType'].enum_type = _ENCODERREQUEST_REQUESTTYPET
_ENCODERREQUEST_REQUESTTYPET.containing_type = _ENCODERREQUEST
_ENCODERRESPONSE.fields_by_name['state'].enum_type = _ENCODERRESPONSE_APPSTATET
_ENCODERRESPONSE_APPSTATET.containing_type = _ENCODERRESPONSE
DESCRIPTOR.message_types_by_name['EncoderRequest'] = _ENCODERREQUEST
DESCRIPTOR.message_types_by_name['EncoderResponse'] = _ENCODERRESPONSE

EncoderRequest = _reflection.GeneratedProtocolMessageType('EncoderRequest', (_message.Message,), dict(
  DESCRIPTOR = _ENCODERREQUEST,
  __module__ = 'Encoder_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.EncoderRequest)
  ))
_sym_db.RegisterMessage(EncoderRequest)

EncoderResponse = _reflection.GeneratedProtocolMessageType('EncoderResponse', (_message.Message,), dict(
  DESCRIPTOR = _ENCODERRESPONSE,
  __module__ = 'Encoder_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.EncoderResponse)
  ))
_sym_db.RegisterMessage(EncoderResponse)


# @@protoc_insertion_point(module_scope)
