# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Ethernet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Ethernet.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x0e\x45thernet.proto\x12\x07mpsqual\"\xa5\x01\n\x0f\x45thernetRequest\x12@\n\x0brequestType\x18\x01 \x02(\x0e\x32%.mpsqual.EthernetRequest.RequestTypeT:\x04STOP\x12\x0f\n\x05local\x18\x02 \x02(\t:\x00\x12\x10\n\x06remote\x18\x03 \x01(\t:\x00\"-\n\x0cRequestTypeT\x12\x08\n\x04STOP\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\n\n\x06REPORT\x10\x02\"\x8c\x01\n\x10\x45thernetResponse\x12\x32\n\x05state\x18\x01 \x02(\x0e\x32#.mpsqual.EthernetResponse.AppStateT\x12\r\n\x05local\x18\x02 \x02(\t\x12\x0e\n\x06result\x18\x03 \x02(\t\"%\n\tAppStateT\x12\x0b\n\x07STOPPED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ETHERNETREQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.EthernetRequest.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=148,
  serialized_end=193,
)
_sym_db.RegisterEnumDescriptor(_ETHERNETREQUEST_REQUESTTYPET)

_ETHERNETRESPONSE_APPSTATET = _descriptor.EnumDescriptor(
  name='AppStateT',
  full_name='mpsqual.EthernetResponse.AppStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=299,
  serialized_end=336,
)
_sym_db.RegisterEnumDescriptor(_ETHERNETRESPONSE_APPSTATET)


_ETHERNETREQUEST = _descriptor.Descriptor(
  name='EthernetRequest',
  full_name='mpsqual.EthernetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.EthernetRequest.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local', full_name='mpsqual.EthernetRequest.local', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remote', full_name='mpsqual.EthernetRequest.remote', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ETHERNETREQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=193,
)


_ETHERNETRESPONSE = _descriptor.Descriptor(
  name='EthernetResponse',
  full_name='mpsqual.EthernetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='mpsqual.EthernetResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local', full_name='mpsqual.EthernetResponse.local', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='mpsqual.EthernetResponse.result', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ETHERNETRESPONSE_APPSTATET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=336,
)

_ETHERNETREQUEST.fields_by_name['requestType'].enum_type = _ETHERNETREQUEST_REQUESTTYPET
_ETHERNETREQUEST_REQUESTTYPET.containing_type = _ETHERNETREQUEST
_ETHERNETRESPONSE.fields_by_name['state'].enum_type = _ETHERNETRESPONSE_APPSTATET
_ETHERNETRESPONSE_APPSTATET.containing_type = _ETHERNETRESPONSE
DESCRIPTOR.message_types_by_name['EthernetRequest'] = _ETHERNETREQUEST
DESCRIPTOR.message_types_by_name['EthernetResponse'] = _ETHERNETRESPONSE

EthernetRequest = _reflection.GeneratedProtocolMessageType('EthernetRequest', (_message.Message,), dict(
  DESCRIPTOR = _ETHERNETREQUEST,
  __module__ = 'Ethernet_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.EthernetRequest)
  ))
_sym_db.RegisterMessage(EthernetRequest)

EthernetResponse = _reflection.GeneratedProtocolMessageType('EthernetResponse', (_message.Message,), dict(
  DESCRIPTOR = _ETHERNETRESPONSE,
  __module__ = 'Ethernet_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.EthernetResponse)
  ))
_sym_db.RegisterMessage(EthernetResponse)


# @@protoc_insertion_point(module_scope)
