# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GPIO.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GPIO.proto',
  package='mpsqual',
  serialized_pb=_b('\n\nGPIO.proto\x12\x07mpsqual\"\xab\x01\n\x0bGPIORequest\x12\x42\n\x0brequestType\x18\x01 \x02(\x0e\x32!.mpsqual.GPIORequest.RequestTypeT:\nDISCONNECT\x12\x0e\n\x04gpIn\x18\x02 \x02(\t:\x00\x12\x0f\n\x05gpOut\x18\x03 \x01(\t:\x00\"7\n\x0cRequestTypeT\x12\x0e\n\nDISCONNECT\x10\x00\x12\x0b\n\x07\x43ONNECT\x10\x01\x12\n\n\x06REPORT\x10\x02\"\xf8\x01\n\x0cGPIOResponse\x12\x30\n\x06status\x18\x01 \x03(\x0b\x32 .mpsqual.GPIOResponse.GpioStatus\x1a\x87\x01\n\nGpioStatus\x12\x31\n\x08\x63onState\x18\x01 \x02(\x0e\x32\x1f.mpsqual.GPIOResponse.ConStateT\x12\x12\n\nmatchCount\x18\x02 \x02(\x05\x12\x15\n\rmismatchCount\x18\x03 \x02(\x05\x12\x0c\n\x04gpIn\x18\x04 \x02(\t\x12\r\n\x05gpOut\x18\x05 \x01(\t\",\n\tConStateT\x12\x10\n\x0c\x44ISCONNECTED\x10\x00\x12\r\n\tCONNECTED\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_GPIOREQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.GPIORequest.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=140,
  serialized_end=195,
)
_sym_db.RegisterEnumDescriptor(_GPIOREQUEST_REQUESTTYPET)

_GPIORESPONSE_CONSTATET = _descriptor.EnumDescriptor(
  name='ConStateT',
  full_name='mpsqual.GPIOResponse.ConStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=402,
  serialized_end=446,
)
_sym_db.RegisterEnumDescriptor(_GPIORESPONSE_CONSTATET)


_GPIOREQUEST = _descriptor.Descriptor(
  name='GPIORequest',
  full_name='mpsqual.GPIORequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.GPIORequest.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gpIn', full_name='mpsqual.GPIORequest.gpIn', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gpOut', full_name='mpsqual.GPIORequest.gpOut', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GPIOREQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=195,
)


_GPIORESPONSE_GPIOSTATUS = _descriptor.Descriptor(
  name='GpioStatus',
  full_name='mpsqual.GPIOResponse.GpioStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conState', full_name='mpsqual.GPIOResponse.GpioStatus.conState', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='matchCount', full_name='mpsqual.GPIOResponse.GpioStatus.matchCount', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mismatchCount', full_name='mpsqual.GPIOResponse.GpioStatus.mismatchCount', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gpIn', full_name='mpsqual.GPIOResponse.GpioStatus.gpIn', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gpOut', full_name='mpsqual.GPIOResponse.GpioStatus.gpOut', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=400,
)

_GPIORESPONSE = _descriptor.Descriptor(
  name='GPIOResponse',
  full_name='mpsqual.GPIOResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='mpsqual.GPIOResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GPIORESPONSE_GPIOSTATUS, ],
  enum_types=[
    _GPIORESPONSE_CONSTATET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=446,
)

_GPIOREQUEST.fields_by_name['requestType'].enum_type = _GPIOREQUEST_REQUESTTYPET
_GPIOREQUEST_REQUESTTYPET.containing_type = _GPIOREQUEST
_GPIORESPONSE_GPIOSTATUS.fields_by_name['conState'].enum_type = _GPIORESPONSE_CONSTATET
_GPIORESPONSE_GPIOSTATUS.containing_type = _GPIORESPONSE
_GPIORESPONSE.fields_by_name['status'].message_type = _GPIORESPONSE_GPIOSTATUS
_GPIORESPONSE_CONSTATET.containing_type = _GPIORESPONSE
DESCRIPTOR.message_types_by_name['GPIORequest'] = _GPIOREQUEST
DESCRIPTOR.message_types_by_name['GPIOResponse'] = _GPIORESPONSE

GPIORequest = _reflection.GeneratedProtocolMessageType('GPIORequest', (_message.Message,), dict(
  DESCRIPTOR = _GPIOREQUEST,
  __module__ = 'GPIO_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.GPIORequest)
  ))
_sym_db.RegisterMessage(GPIORequest)

GPIOResponse = _reflection.GeneratedProtocolMessageType('GPIOResponse', (_message.Message,), dict(

  GpioStatus = _reflection.GeneratedProtocolMessageType('GpioStatus', (_message.Message,), dict(
    DESCRIPTOR = _GPIORESPONSE_GPIOSTATUS,
    __module__ = 'GPIO_pb2'
    # @@protoc_insertion_point(class_scope:mpsqual.GPIOResponse.GpioStatus)
    ))
  ,
  DESCRIPTOR = _GPIORESPONSE,
  __module__ = 'GPIO_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.GPIOResponse)
  ))
_sym_db.RegisterMessage(GPIOResponse)
_sym_db.RegisterMessage(GPIOResponse.GpioStatus)


# @@protoc_insertion_point(module_scope)
