# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HDDS.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HDDS.proto',
  package='mpsqual',
  serialized_pb=_b('\n\nHDDS.proto\x12\x07mpsqual\"\x15\n\x06GetReq\x12\x0b\n\x03key\x18\x01 \x03(\t\"-\n\x07GetResp\x12\"\n\x06values\x18\x01 \x03(\x0b\x32\x12.mpsqual.ValueResp\"+\n\x06SetReq\x12!\n\x06values\x18\x01 \x03(\x0b\x32\x11.mpsqual.Property\"1\n\x0bHDDSSetResp\x12\"\n\x06values\x18\x01 \x03(\x0b\x32\x12.mpsqual.ValueResp\"g\n\tValueResp\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12#\n\x08keyValue\x18\x02 \x02(\x0b\x32\x11.mpsqual.Property\x12$\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x15.mpsqual.ErrorMessage\"&\n\x08Property\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"=\n\x0c\x45rrorMessage\x12\x12\n\nerror_code\x18\x01 \x02(\r\x12\x19\n\x11\x65rror_description\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETREQ = _descriptor.Descriptor(
  name='GetReq',
  full_name='mpsqual.GetReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mpsqual.GetReq.key', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=44,
)


_GETRESP = _descriptor.Descriptor(
  name='GetResp',
  full_name='mpsqual.GetResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='mpsqual.GetResp.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=91,
)


_SETREQ = _descriptor.Descriptor(
  name='SetReq',
  full_name='mpsqual.SetReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='mpsqual.SetReq.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=136,
)


_HDDSSETRESP = _descriptor.Descriptor(
  name='HDDSSetResp',
  full_name='mpsqual.HDDSSetResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='mpsqual.HDDSSetResp.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=187,
)


_VALUERESP = _descriptor.Descriptor(
  name='ValueResp',
  full_name='mpsqual.ValueResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='mpsqual.ValueResp.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keyValue', full_name='mpsqual.ValueResp.keyValue', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='mpsqual.ValueResp.error', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=292,
)


_PROPERTY = _descriptor.Descriptor(
  name='Property',
  full_name='mpsqual.Property',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mpsqual.Property.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='mpsqual.Property.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=332,
)


_ERRORMESSAGE = _descriptor.Descriptor(
  name='ErrorMessage',
  full_name='mpsqual.ErrorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='mpsqual.ErrorMessage.error_code', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_description', full_name='mpsqual.ErrorMessage.error_description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=395,
)

_GETRESP.fields_by_name['values'].message_type = _VALUERESP
_SETREQ.fields_by_name['values'].message_type = _PROPERTY
_HDDSSETRESP.fields_by_name['values'].message_type = _VALUERESP
_VALUERESP.fields_by_name['keyValue'].message_type = _PROPERTY
_VALUERESP.fields_by_name['error'].message_type = _ERRORMESSAGE
DESCRIPTOR.message_types_by_name['GetReq'] = _GETREQ
DESCRIPTOR.message_types_by_name['GetResp'] = _GETRESP
DESCRIPTOR.message_types_by_name['SetReq'] = _SETREQ
DESCRIPTOR.message_types_by_name['HDDSSetResp'] = _HDDSSETRESP
DESCRIPTOR.message_types_by_name['ValueResp'] = _VALUERESP
DESCRIPTOR.message_types_by_name['Property'] = _PROPERTY
DESCRIPTOR.message_types_by_name['ErrorMessage'] = _ERRORMESSAGE

GetReq = _reflection.GeneratedProtocolMessageType('GetReq', (_message.Message,), dict(
  DESCRIPTOR = _GETREQ,
  __module__ = 'HDDS_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.GetReq)
  ))
_sym_db.RegisterMessage(GetReq)

GetResp = _reflection.GeneratedProtocolMessageType('GetResp', (_message.Message,), dict(
  DESCRIPTOR = _GETRESP,
  __module__ = 'HDDS_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.GetResp)
  ))
_sym_db.RegisterMessage(GetResp)

SetReq = _reflection.GeneratedProtocolMessageType('SetReq', (_message.Message,), dict(
  DESCRIPTOR = _SETREQ,
  __module__ = 'HDDS_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.SetReq)
  ))
_sym_db.RegisterMessage(SetReq)

HDDSSetResp = _reflection.GeneratedProtocolMessageType('HDDSSetResp', (_message.Message,), dict(
  DESCRIPTOR = _HDDSSETRESP,
  __module__ = 'HDDS_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.HDDSSetResp)
  ))
_sym_db.RegisterMessage(HDDSSetResp)

ValueResp = _reflection.GeneratedProtocolMessageType('ValueResp', (_message.Message,), dict(
  DESCRIPTOR = _VALUERESP,
  __module__ = 'HDDS_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.ValueResp)
  ))
_sym_db.RegisterMessage(ValueResp)

Property = _reflection.GeneratedProtocolMessageType('Property', (_message.Message,), dict(
  DESCRIPTOR = _PROPERTY,
  __module__ = 'HDDS_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.Property)
  ))
_sym_db.RegisterMessage(Property)

ErrorMessage = _reflection.GeneratedProtocolMessageType('ErrorMessage', (_message.Message,), dict(
  DESCRIPTOR = _ERRORMESSAGE,
  __module__ = 'HDDS_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.ErrorMessage)
  ))
_sym_db.RegisterMessage(ErrorMessage)


# @@protoc_insertion_point(module_scope)
