# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MemoryBandwidth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MemoryBandwidth.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x15MemoryBandwidth.proto\x12\x07mpsqual\"\x90\x01\n\x16MemoryBandwidthRequest\x12G\n\x0brequestType\x18\x01 \x02(\x0e\x32,.mpsqual.MemoryBandwidthRequest.RequestTypeT:\x04STOP\"-\n\x0cRequestTypeT\x12\x08\n\x04STOP\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\n\n\x06REPORT\x10\x02\"\x94\x01\n\x17MemoryBandwidthResponse\x12\x39\n\x05state\x18\x01 \x02(\x0e\x32*.mpsqual.MemoryBandwidthResponse.AppStateT\x12\x17\n\x0fmemoryBandWidth\x18\x02 \x02(\x02\"%\n\tAppStateT\x12\x0b\n\x07STOPPED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MEMORYBANDWIDTHREQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.MemoryBandwidthRequest.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=134,
  serialized_end=179,
)
_sym_db.RegisterEnumDescriptor(_MEMORYBANDWIDTHREQUEST_REQUESTTYPET)

_MEMORYBANDWIDTHRESPONSE_APPSTATET = _descriptor.EnumDescriptor(
  name='AppStateT',
  full_name='mpsqual.MemoryBandwidthResponse.AppStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=293,
  serialized_end=330,
)
_sym_db.RegisterEnumDescriptor(_MEMORYBANDWIDTHRESPONSE_APPSTATET)


_MEMORYBANDWIDTHREQUEST = _descriptor.Descriptor(
  name='MemoryBandwidthRequest',
  full_name='mpsqual.MemoryBandwidthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.MemoryBandwidthRequest.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MEMORYBANDWIDTHREQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=179,
)


_MEMORYBANDWIDTHRESPONSE = _descriptor.Descriptor(
  name='MemoryBandwidthResponse',
  full_name='mpsqual.MemoryBandwidthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='mpsqual.MemoryBandwidthResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='memoryBandWidth', full_name='mpsqual.MemoryBandwidthResponse.memoryBandWidth', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MEMORYBANDWIDTHRESPONSE_APPSTATET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=330,
)

_MEMORYBANDWIDTHREQUEST.fields_by_name['requestType'].enum_type = _MEMORYBANDWIDTHREQUEST_REQUESTTYPET
_MEMORYBANDWIDTHREQUEST_REQUESTTYPET.containing_type = _MEMORYBANDWIDTHREQUEST
_MEMORYBANDWIDTHRESPONSE.fields_by_name['state'].enum_type = _MEMORYBANDWIDTHRESPONSE_APPSTATET
_MEMORYBANDWIDTHRESPONSE_APPSTATET.containing_type = _MEMORYBANDWIDTHRESPONSE
DESCRIPTOR.message_types_by_name['MemoryBandwidthRequest'] = _MEMORYBANDWIDTHREQUEST
DESCRIPTOR.message_types_by_name['MemoryBandwidthResponse'] = _MEMORYBANDWIDTHRESPONSE

MemoryBandwidthRequest = _reflection.GeneratedProtocolMessageType('MemoryBandwidthRequest', (_message.Message,), dict(
  DESCRIPTOR = _MEMORYBANDWIDTHREQUEST,
  __module__ = 'MemoryBandwidth_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.MemoryBandwidthRequest)
  ))
_sym_db.RegisterMessage(MemoryBandwidthRequest)

MemoryBandwidthResponse = _reflection.GeneratedProtocolMessageType('MemoryBandwidthResponse', (_message.Message,), dict(
  DESCRIPTOR = _MEMORYBANDWIDTHRESPONSE,
  __module__ = 'MemoryBandwidth_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.MemoryBandwidthResponse)
  ))
_sym_db.RegisterMessage(MemoryBandwidthResponse)


# @@protoc_insertion_point(module_scope)
