# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RemoteInventory.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RemoteInventory.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x15RemoteInventory.proto\x12\x07mpsqual\"\x18\n\x16RemoteInventoryRequest\",\n\x17RemoteInventoryResponse\x12\x11\n\tinventory\x18\x01 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REMOTEINVENTORYREQUEST = _descriptor.Descriptor(
  name='RemoteInventoryRequest',
  full_name='mpsqual.RemoteInventoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=58,
)


_REMOTEINVENTORYRESPONSE = _descriptor.Descriptor(
  name='RemoteInventoryResponse',
  full_name='mpsqual.RemoteInventoryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inventory', full_name='mpsqual.RemoteInventoryResponse.inventory', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['RemoteInventoryRequest'] = _REMOTEINVENTORYREQUEST
DESCRIPTOR.message_types_by_name['RemoteInventoryResponse'] = _REMOTEINVENTORYRESPONSE

RemoteInventoryRequest = _reflection.GeneratedProtocolMessageType('RemoteInventoryRequest', (_message.Message,), dict(
  DESCRIPTOR = _REMOTEINVENTORYREQUEST,
  __module__ = 'RemoteInventory_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.RemoteInventoryRequest)
  ))
_sym_db.RegisterMessage(RemoteInventoryRequest)

RemoteInventoryResponse = _reflection.GeneratedProtocolMessageType('RemoteInventoryResponse', (_message.Message,), dict(
  DESCRIPTOR = _REMOTEINVENTORYRESPONSE,
  __module__ = 'RemoteInventory_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.RemoteInventoryResponse)
  ))
_sym_db.RegisterMessage(RemoteInventoryResponse)


# @@protoc_insertion_point(module_scope)
