# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RS232.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RS232.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x0bRS232.proto\x12\x07mpsqual\"|\n\x0cRS232Request\x12=\n\x0brequestType\x18\x01 \x02(\x0e\x32\".mpsqual.RS232Request.RequestTypeT:\x04STOP\"-\n\x0cRequestTypeT\x12\x08\n\x04STOP\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\n\n\x06REPORT\x10\x02\"\x92\x01\n\rRS232Response\x12/\n\x05state\x18\x01 \x02(\x0e\x32 .mpsqual.RS232Response.AppStateT\x12\x12\n\x07matches\x18\x02 \x02(\r:\x01\x30\x12\x15\n\nmismatches\x18\x03 \x02(\r:\x01\x30\"%\n\tAppStateT\x12\x0b\n\x07STOPPED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RS232REQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.RS232Request.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=103,
  serialized_end=148,
)
_sym_db.RegisterEnumDescriptor(_RS232REQUEST_REQUESTTYPET)

_RS232RESPONSE_APPSTATET = _descriptor.EnumDescriptor(
  name='AppStateT',
  full_name='mpsqual.RS232Response.AppStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=260,
  serialized_end=297,
)
_sym_db.RegisterEnumDescriptor(_RS232RESPONSE_APPSTATET)


_RS232REQUEST = _descriptor.Descriptor(
  name='RS232Request',
  full_name='mpsqual.RS232Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.RS232Request.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RS232REQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=148,
)


_RS232RESPONSE = _descriptor.Descriptor(
  name='RS232Response',
  full_name='mpsqual.RS232Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='mpsqual.RS232Response.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='matches', full_name='mpsqual.RS232Response.matches', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mismatches', full_name='mpsqual.RS232Response.mismatches', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RS232RESPONSE_APPSTATET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=297,
)

_RS232REQUEST.fields_by_name['requestType'].enum_type = _RS232REQUEST_REQUESTTYPET
_RS232REQUEST_REQUESTTYPET.containing_type = _RS232REQUEST
_RS232RESPONSE.fields_by_name['state'].enum_type = _RS232RESPONSE_APPSTATET
_RS232RESPONSE_APPSTATET.containing_type = _RS232RESPONSE
DESCRIPTOR.message_types_by_name['RS232Request'] = _RS232REQUEST
DESCRIPTOR.message_types_by_name['RS232Response'] = _RS232RESPONSE

RS232Request = _reflection.GeneratedProtocolMessageType('RS232Request', (_message.Message,), dict(
  DESCRIPTOR = _RS232REQUEST,
  __module__ = 'RS232_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.RS232Request)
  ))
_sym_db.RegisterMessage(RS232Request)

RS232Response = _reflection.GeneratedProtocolMessageType('RS232Response', (_message.Message,), dict(
  DESCRIPTOR = _RS232RESPONSE,
  __module__ = 'RS232_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.RS232Response)
  ))
_sym_db.RegisterMessage(RS232Response)


# @@protoc_insertion_point(module_scope)
