# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RS485.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RS485.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x0bRS485.proto\x12\x07mpsqual\"|\n\x0cRS485Request\x12=\n\x0brequestType\x18\x01 \x02(\x0e\x32\".mpsqual.RS485Request.RequestTypeT:\x04STOP\"-\n\x0cRequestTypeT\x12\x08\n\x04STOP\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\n\n\x06REPORT\x10\x02\"\x8c\x01\n\rRS485Response\x12/\n\x05state\x18\x01 \x02(\x0e\x32 .mpsqual.RS485Response.AppStateT\x12\x0f\n\x07matches\x18\x02 \x02(\r\x12\x12\n\nmismatches\x18\x03 \x02(\r\"%\n\tAppStateT\x12\x0b\n\x07STOPPED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RS485REQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.RS485Request.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPORT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=103,
  serialized_end=148,
)
_sym_db.RegisterEnumDescriptor(_RS485REQUEST_REQUESTTYPET)

_RS485RESPONSE_APPSTATET = _descriptor.EnumDescriptor(
  name='AppStateT',
  full_name='mpsqual.RS485Response.AppStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=254,
  serialized_end=291,
)
_sym_db.RegisterEnumDescriptor(_RS485RESPONSE_APPSTATET)


_RS485REQUEST = _descriptor.Descriptor(
  name='RS485Request',
  full_name='mpsqual.RS485Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.RS485Request.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RS485REQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=148,
)


_RS485RESPONSE = _descriptor.Descriptor(
  name='RS485Response',
  full_name='mpsqual.RS485Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='mpsqual.RS485Response.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='matches', full_name='mpsqual.RS485Response.matches', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mismatches', full_name='mpsqual.RS485Response.mismatches', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RS485RESPONSE_APPSTATET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=291,
)

_RS485REQUEST.fields_by_name['requestType'].enum_type = _RS485REQUEST_REQUESTTYPET
_RS485REQUEST_REQUESTTYPET.containing_type = _RS485REQUEST
_RS485RESPONSE.fields_by_name['state'].enum_type = _RS485RESPONSE_APPSTATET
_RS485RESPONSE_APPSTATET.containing_type = _RS485RESPONSE
DESCRIPTOR.message_types_by_name['RS485Request'] = _RS485REQUEST
DESCRIPTOR.message_types_by_name['RS485Response'] = _RS485RESPONSE

RS485Request = _reflection.GeneratedProtocolMessageType('RS485Request', (_message.Message,), dict(
  DESCRIPTOR = _RS485REQUEST,
  __module__ = 'RS485_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.RS485Request)
  ))
_sym_db.RegisterMessage(RS485Request)

RS485Response = _reflection.GeneratedProtocolMessageType('RS485Response', (_message.Message,), dict(
  DESCRIPTOR = _RS485RESPONSE,
  __module__ = 'RS485_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.RS485Response)
  ))
_sym_db.RegisterMessage(RS485Response)


# @@protoc_insertion_point(module_scope)
