# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SEMA.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SEMA.proto',
  package='mpsqual',
  serialized_pb=_b('\n\nSEMA.proto\x12\x07mpsqual\"$\n\x14RequestStatusMessage\x12\x0c\n\x04name\x18\x01 \x02(\t\"\xba\x01\n\x0fResponseMessage\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x35\n\x05\x65rror\x18\x02 \x02(\x0e\x32&.mpsqual.ResponseMessage.ErrStatusCode\x12\r\n\x05value\x18\x03 \x01(\t\"S\n\rErrStatusCode\x12\x06\n\x02OK\x10\x00\x12\x10\n\x0cINVALID_NAME\x10\x01\x12\x15\n\x11SEMA_ACCESS_ERROR\x10\x02\x12\x11\n\rUNKNOWN_ERROR\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RESPONSEMESSAGE_ERRSTATUSCODE = _descriptor.EnumDescriptor(
  name='ErrStatusCode',
  full_name='mpsqual.ResponseMessage.ErrStatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_NAME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEMA_ACCESS_ERROR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ERROR', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=165,
  serialized_end=248,
)
_sym_db.RegisterEnumDescriptor(_RESPONSEMESSAGE_ERRSTATUSCODE)


_REQUESTSTATUSMESSAGE = _descriptor.Descriptor(
  name='RequestStatusMessage',
  full_name='mpsqual.RequestStatusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mpsqual.RequestStatusMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=59,
)


_RESPONSEMESSAGE = _descriptor.Descriptor(
  name='ResponseMessage',
  full_name='mpsqual.ResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mpsqual.ResponseMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='mpsqual.ResponseMessage.error', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='mpsqual.ResponseMessage.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSEMESSAGE_ERRSTATUSCODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=248,
)

_RESPONSEMESSAGE.fields_by_name['error'].enum_type = _RESPONSEMESSAGE_ERRSTATUSCODE
_RESPONSEMESSAGE_ERRSTATUSCODE.containing_type = _RESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['RequestStatusMessage'] = _REQUESTSTATUSMESSAGE
DESCRIPTOR.message_types_by_name['ResponseMessage'] = _RESPONSEMESSAGE

RequestStatusMessage = _reflection.GeneratedProtocolMessageType('RequestStatusMessage', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTSTATUSMESSAGE,
  __module__ = 'SEMA_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.RequestStatusMessage)
  ))
_sym_db.RegisterMessage(RequestStatusMessage)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEMESSAGE,
  __module__ = 'SEMA_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.ResponseMessage)
  ))
_sym_db.RegisterMessage(ResponseMessage)


# @@protoc_insertion_point(module_scope)
