# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SSD.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SSD.proto',
  package='mpsqual',
  serialized_pb=_b('\n\tSSD.proto\x12\x07mpsqual\"l\n\nSSDRequest\x12;\n\x0brequestType\x18\x01 \x02(\x0e\x32 .mpsqual.SSDRequest.RequestTypeT:\x04STOP\"!\n\x0cRequestTypeT\x12\x08\n\x04STOP\x10\x00\x12\x07\n\x03RUN\x10\x01\"c\n\x0bSSDResponse\x12-\n\x05state\x18\x01 \x02(\x0e\x32\x1e.mpsqual.SSDResponse.AppStateT\"%\n\tAppStateT\x12\x0b\n\x07STOPPED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SSDREQUEST_REQUESTTYPET = _descriptor.EnumDescriptor(
  name='RequestTypeT',
  full_name='mpsqual.SSDRequest.RequestTypeT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=97,
  serialized_end=130,
)
_sym_db.RegisterEnumDescriptor(_SSDREQUEST_REQUESTTYPET)

_SSDRESPONSE_APPSTATET = _descriptor.EnumDescriptor(
  name='AppStateT',
  full_name='mpsqual.SSDResponse.AppStateT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=194,
  serialized_end=231,
)
_sym_db.RegisterEnumDescriptor(_SSDRESPONSE_APPSTATET)


_SSDREQUEST = _descriptor.Descriptor(
  name='SSDRequest',
  full_name='mpsqual.SSDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='mpsqual.SSDRequest.requestType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SSDREQUEST_REQUESTTYPET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=130,
)


_SSDRESPONSE = _descriptor.Descriptor(
  name='SSDResponse',
  full_name='mpsqual.SSDResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='mpsqual.SSDResponse.state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SSDRESPONSE_APPSTATET,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=231,
)

_SSDREQUEST.fields_by_name['requestType'].enum_type = _SSDREQUEST_REQUESTTYPET
_SSDREQUEST_REQUESTTYPET.containing_type = _SSDREQUEST
_SSDRESPONSE.fields_by_name['state'].enum_type = _SSDRESPONSE_APPSTATET
_SSDRESPONSE_APPSTATET.containing_type = _SSDRESPONSE
DESCRIPTOR.message_types_by_name['SSDRequest'] = _SSDREQUEST
DESCRIPTOR.message_types_by_name['SSDResponse'] = _SSDRESPONSE

SSDRequest = _reflection.GeneratedProtocolMessageType('SSDRequest', (_message.Message,), dict(
  DESCRIPTOR = _SSDREQUEST,
  __module__ = 'SSD_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.SSDRequest)
  ))
_sym_db.RegisterMessage(SSDRequest)

SSDResponse = _reflection.GeneratedProtocolMessageType('SSDResponse', (_message.Message,), dict(
  DESCRIPTOR = _SSDRESPONSE,
  __module__ = 'SSD_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.SSDResponse)
  ))
_sym_db.RegisterMessage(SSDResponse)


# @@protoc_insertion_point(module_scope)
