# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SystemMonitoring.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SystemMonitoring.proto',
  package='mpsqual',
  serialized_pb=_b('\n\x16SystemMonitoring.proto\x12\x07mpsqual\"\x19\n\x17SystemMonitoringRequest\"\x9a\x03\n\x18SystemMonitoringResponse\x12L\n\x15powerSupplyStatistics\x18\x01 \x03(\x0b\x32-.mpsqual.SystemMonitoringResponse.SensorValue\x12\x43\n\x0esemaStatistics\x18\x02 \x03(\x0b\x32+.mpsqual.SystemMonitoringResponse.SemaValue\x12@\n\nswitchData\x18\x03 \x02(\x0b\x32,.mpsqual.SystemMonitoringResponse.SwitchData\x1a\x44\n\x0bSensorValue\x12\x12\n\ndeviceName\x18\x01 \x02(\t\x12\x12\n\nsensorName\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x02(\t\x1a,\n\tSemaValue\x12\x10\n\x08itemName\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x1a\x35\n\nSwitchData\x12\x13\n\x0btemperature\x18\x01 \x02(\t\x12\x12\n\nstatistics\x18\x02 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SYSTEMMONITORINGREQUEST = _descriptor.Descriptor(
  name='SystemMonitoringRequest',
  full_name='mpsqual.SystemMonitoringRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=60,
)


_SYSTEMMONITORINGRESPONSE_SENSORVALUE = _descriptor.Descriptor(
  name='SensorValue',
  full_name='mpsqual.SystemMonitoringResponse.SensorValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceName', full_name='mpsqual.SystemMonitoringResponse.SensorValue.deviceName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensorName', full_name='mpsqual.SystemMonitoringResponse.SensorValue.sensorName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='mpsqual.SystemMonitoringResponse.SensorValue.value', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=372,
)

_SYSTEMMONITORINGRESPONSE_SEMAVALUE = _descriptor.Descriptor(
  name='SemaValue',
  full_name='mpsqual.SystemMonitoringResponse.SemaValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemName', full_name='mpsqual.SystemMonitoringResponse.SemaValue.itemName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='mpsqual.SystemMonitoringResponse.SemaValue.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=418,
)

_SYSTEMMONITORINGRESPONSE_SWITCHDATA = _descriptor.Descriptor(
  name='SwitchData',
  full_name='mpsqual.SystemMonitoringResponse.SwitchData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='mpsqual.SystemMonitoringResponse.SwitchData.temperature', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statistics', full_name='mpsqual.SystemMonitoringResponse.SwitchData.statistics', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=473,
)

_SYSTEMMONITORINGRESPONSE = _descriptor.Descriptor(
  name='SystemMonitoringResponse',
  full_name='mpsqual.SystemMonitoringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='powerSupplyStatistics', full_name='mpsqual.SystemMonitoringResponse.powerSupplyStatistics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='semaStatistics', full_name='mpsqual.SystemMonitoringResponse.semaStatistics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='switchData', full_name='mpsqual.SystemMonitoringResponse.switchData', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SYSTEMMONITORINGRESPONSE_SENSORVALUE, _SYSTEMMONITORINGRESPONSE_SEMAVALUE, _SYSTEMMONITORINGRESPONSE_SWITCHDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=473,
)

_SYSTEMMONITORINGRESPONSE_SENSORVALUE.containing_type = _SYSTEMMONITORINGRESPONSE
_SYSTEMMONITORINGRESPONSE_SEMAVALUE.containing_type = _SYSTEMMONITORINGRESPONSE
_SYSTEMMONITORINGRESPONSE_SWITCHDATA.containing_type = _SYSTEMMONITORINGRESPONSE
_SYSTEMMONITORINGRESPONSE.fields_by_name['powerSupplyStatistics'].message_type = _SYSTEMMONITORINGRESPONSE_SENSORVALUE
_SYSTEMMONITORINGRESPONSE.fields_by_name['semaStatistics'].message_type = _SYSTEMMONITORINGRESPONSE_SEMAVALUE
_SYSTEMMONITORINGRESPONSE.fields_by_name['switchData'].message_type = _SYSTEMMONITORINGRESPONSE_SWITCHDATA
DESCRIPTOR.message_types_by_name['SystemMonitoringRequest'] = _SYSTEMMONITORINGREQUEST
DESCRIPTOR.message_types_by_name['SystemMonitoringResponse'] = _SYSTEMMONITORINGRESPONSE

SystemMonitoringRequest = _reflection.GeneratedProtocolMessageType('SystemMonitoringRequest', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMMONITORINGREQUEST,
  __module__ = 'SystemMonitoring_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.SystemMonitoringRequest)
  ))
_sym_db.RegisterMessage(SystemMonitoringRequest)

SystemMonitoringResponse = _reflection.GeneratedProtocolMessageType('SystemMonitoringResponse', (_message.Message,), dict(

  SensorValue = _reflection.GeneratedProtocolMessageType('SensorValue', (_message.Message,), dict(
    DESCRIPTOR = _SYSTEMMONITORINGRESPONSE_SENSORVALUE,
    __module__ = 'SystemMonitoring_pb2'
    # @@protoc_insertion_point(class_scope:mpsqual.SystemMonitoringResponse.SensorValue)
    ))
  ,

  SemaValue = _reflection.GeneratedProtocolMessageType('SemaValue', (_message.Message,), dict(
    DESCRIPTOR = _SYSTEMMONITORINGRESPONSE_SEMAVALUE,
    __module__ = 'SystemMonitoring_pb2'
    # @@protoc_insertion_point(class_scope:mpsqual.SystemMonitoringResponse.SemaValue)
    ))
  ,

  SwitchData = _reflection.GeneratedProtocolMessageType('SwitchData', (_message.Message,), dict(
    DESCRIPTOR = _SYSTEMMONITORINGRESPONSE_SWITCHDATA,
    __module__ = 'SystemMonitoring_pb2'
    # @@protoc_insertion_point(class_scope:mpsqual.SystemMonitoringResponse.SwitchData)
    ))
  ,
  DESCRIPTOR = _SYSTEMMONITORINGRESPONSE,
  __module__ = 'SystemMonitoring_pb2'
  # @@protoc_insertion_point(class_scope:mpsqual.SystemMonitoringResponse)
  ))
_sym_db.RegisterMessage(SystemMonitoringResponse)
_sym_db.RegisterMessage(SystemMonitoringResponse.SensorValue)
_sym_db.RegisterMessage(SystemMonitoringResponse.SemaValue)
_sym_db.RegisterMessage(SystemMonitoringResponse.SwitchData)


# @@protoc_insertion_point(module_scope)
